const StocksData = [
  {
    id: 1,
    stockName: "Indian Tobacco Limited",
    stockSymbl: "ITC",
    current_price: 450.0,
    category: "FMCG",
  },
  {
    id: 2,
    stockName: "Adani Wilmar Limited",
    stockSymbl: "AWL",
    current_price: 300.0,
    category: "FMCG",
  },
  {
    id: 3,
    stockName: "Reliance Industries",
    stockSymbl: "RELI",
    current_price: 2500.0,
    category: "Energy",
  },
  {
    id: 4,
    stockName: "Tata Consultancy Services",
    stockSymbl: "TCS",
    current_price: 3500.0,
    category: "IT",
  },
  {
    id: 5,
    stockName: "HDFC Bank",
    stockSymbl: "HDFC",
    current_price: 1600.0,
    category: "Banking",
  },
  {
    id: 6,
    stockName: "Infosys",
    stockSymbl: "INFY",
    current_price: 1400.0,
    category: "IT",
  },
  {
    id: 7,
    stockName: "Larsen & Toubro",
    stockSymbl: "LT",
    current_price: 1700.0,
    category: "Construction",
  },
  {
    id: 8,
    stockName: "Asian Paints",
    stockSymbl: "ASPN",
    current_price: 3100.0,
    category: "Chemicals",
  },
  {
    id: 9,
    stockName: "Hindustan Unilever",
    stockSymbl: "HUL",
    current_price: 2300.0,
    category: "FMCG",
  },
  {
    id: 10,
    stockName: "Maruti Suzuki",
    stockSymbl: "MSIL",
    current_price: 7500.0,
    category: "Automobile",
  },
  {
    id: 11,
    stockName: "Bharti Airtel",
    stockSymbl: "BHARTIARTL",
    current_price: 600.0,
    category: "Telecom",
  },
  {
    id: 12,
    stockName: "State Bank of India",
    stockSymbl: "SBI",
    current_price: 450.0,
    category: "Banking",
  },
  {
    id: 13,
    stockName: "Sun Pharmaceutical",
    stockSymbl: "SUNPHARMA",
    current_price: 800.0,
    category: "Pharmaceutical",
  },
  {
    id: 14,
    stockName: "Mahindra & Mahindra",
    stockSymbl: "M&M",
    current_price: 1250.0,
    category: "Automobile",
  },
  {
    id: 15,
    stockName: "ICICI Bank",
    stockSymbl: "ICICIBANK",
    current_price: 950.0,
    category: "Banking",
  },
  {
    id: 16,
    stockName: "Wipro",
    stockSymbl: "WIPRO",
    current_price: 420.0,
    category: "IT",
  },
  {
    id: 17,
    stockName: "Kotak Mahindra Bank",
    stockSymbl: "KOTAKBANK",
    current_price: 1800.0,
    category: "Banking",
  },
  {
    id: 18,
    stockName: "Bajaj Finserv",
    stockSymbl: "BAJAJFINSV",
    current_price: 13000.0,
    category: "Finance",
  },
  {
    id: 19,
    stockName: "Titan Company",
    stockSymbl: "TITAN",
    current_price: 2300.0,
    category: "Retail",
  },
  {
    id: 20,
    stockName: "Oil and Natural Gas Corporation",
    stockSymbl: "ONGC",
    current_price: 160.0,
    category: "Energy",
  },
];
export default StocksData;
